version: "3.8"
services:
  scrapy_app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: data_ingestion_scrapy_app
    command: ["sleep", "infinity"]
    volumes:
      - ./jobs_project:/app/jobs_project
      - ./infra:/app/infra
      - ./query.py:/app/query.py
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=data_ingestion_db
      - REDIS_URI=redis://redis:6379/0
      - PYTHONPATH=/app:$PYTHONPATH
    env_file:
      - .env
  mongodb:
    image: mongo:6.0
    container_name: data_ingestion_mongo_db
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db # will be persisting locally as well
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: data_ingestion_redis_cache
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data # will be persisting locally as well
    restart: unless-stopped
volumes:
  mongo_data:
  redis_data: